Catalog/Catalog/Controllers/ClasaController.cs
using Catalog.BusinessLogic;
using Catalog.Model;
using System.Web.Mvc;

namespace Catalog.Controllers
{
    [Authorize(Roles = "Admin,Profesor")]
    public class ClasaController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var listaClase = new ClasaBusiness().GetClase();
            var loggedUser = User.Identity.Name;

            return View(listaClase);
        }

        [HttpGet]
        public ActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult Create(ClasaModel clasaModel)
        {
            if (ModelState.IsValid)
            {
                new ClasaBusiness().Insert(clasaModel);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            new ClasaBusiness().Delete(id);

            return View("index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = new ClasaBusiness().Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, ClasaModel clasa)
        {
            if (ModelState.IsValid)
            {
                new ClasaBusiness().Update(clasa);
            }
            return View();
        }
    }
}

Catalog/Catalog/Controllers/ElevController.cs
using Catalog.BusinessLogic;
using Catalog.Model;
using System.Web.Mvc;

namespace Catalog.Controllers
{
    [Authorize(Roles = "Admin,Profesor")]
    public class ElevController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var listaUtilizatori = new ElevBusiness().GetElevi();
            var loggedUser = User.Identity.Name;

            return View(listaUtilizatori);
        }
                
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ElevModel elevModel)
        {
            if (ModelState.IsValid)
            {
                new ElevBusiness().Insert(elevModel);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            new ElevBusiness().Delete(id);

            return View("index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = new ElevBusiness().Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, ElevModel elev)
        {
            if (ModelState.IsValid)
            {
                new ElevBusiness().Update(elev);
            }
            return View();
        }
    }
}

Catalog/Catalog/Controllers/MaterieController.cs
using Catalog.BusinessLogic;
using Catalog.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Catalog.Controllers
{
    public class MaterieController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var listaMaterii = new MaterieBusiness().GetMaterii();
            return View(listaMaterii);
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        public ActionResult Create(MaterieModel materieModel)
        {
            if (ModelState.IsValid)
            {
                new MaterieBusiness().Insert(materieModel);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Materie/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Materie/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Materie/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Materie/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Catalog/Catalog/Controllers/ProfesorController.cs
using Catalog.BusinessLogic;
using Catalog.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Catalog.Controllers
{
    public class ProfesorController : Controller
    {
        [Authorize(Roles = "Admin,Profesor")]
        [HttpGet]
        public ActionResult Index()
        {
            var listaProfesori = new ProfesorBusiness().GetProfessors();
            var loggedUser = User.Identity.Name;

            return View(listaProfesori);
        }

        [Authorize(Roles = "Admin")]        
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Role = "Admin";
            ViewBag.Functii = ProfesorBusiness.GetFunctions("Admin");
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(ProfesorModel profesorModel)
        {
            if (ModelState.IsValid)
            {
                new ProfesorBusiness().Insert(profesorModel);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            new ProfesorBusiness().Delete(id);

            return View();
        }

        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = new ProfesorBusiness().Get(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(int id, ProfesorModel profesor)
        {
            if (ModelState.IsValid)
            {
                new ProfesorBusiness().Update(profesor);
            }
            return View();
        }
    }
}

Catalog/Catalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Catalog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Profesori", "Index", "Profesor", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Materii", "Index", "Materie", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Elevi", "Index", "Elev", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Clase", "Index", "Clasa", new { area = "" }, new { @class = "navbar-brand" })

                @Html.ActionLink("Delogare", "Logout", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; G-A Matei @DateTime.Now </p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>